syntax on
colorscheme murphy
set number
set autoindent
set textwidth=80
"set tabstop=4
"set shiftwidth=0
"set expandtab
"set softtabstop=4
set hlsearch
set incsearch
set showcmd
set hidden
set ruler
set autochdir
set nojoinspaces
set wildmenu
set listchars=tab:›\ ,trail:·,nbsp:␣,extends:⟩,precedes:⟨
set list
